### ISSUE TITLE
How to recognize/convert other secret keys except for base32?

### ISSUE THREAD

**Issue by tsdh** [juergenhoetzel/emacs-totp#3]
Hi, I've successfully set up totp for sr.ht and github by converting the secret key using `base32 -d <<<KEY|xxd -g0 -p` as documented in the README.md.

However, the secrets from, e.g., my Firefox account, seem to be in some other format.  The format there is 13 space-separated blocks of 4 capital letters/digits each.  When fed into `base32`, that complains about "invalid input".  Removing the spaces didn't help.

Compared to the working base32 secrets from sr.ht and github, the only difference I can see is that Firefox secret is longer but the sr.ht/github secrets consist of only capital letters and digits, too.

Because I didn't know better, I've tried my luck with `base64 -d <<<KEY|xxd -g0 -p` which doesn't error but produces a two-line hex key.  I've tried using that without the newline but it produced invalid (and different to my phone's authenticator app's initialized with the same secret) keys.

Do you know by chance how to figure out the format of a secret?  Apparently the authenticator app on the phone DTRT for the secrets of all those sites, no matter the difference.

**Comment by juergenhoetzel** [comment]
> 13 space-separated blocks of 4 capital letters

I tried to reproduce this issue by creating an account on https://accounts.firefox.com/ but the 2FA  only created a  standard 20-byte secret (32 chars base64-encoded secret).

**Comment by tsdh** [comment]
Hm, strange.  Amazon has the same secrets format.

And codeberg.org has a 64 character secret which `base32` processes without error but when using the hex version, other (invalid) keys are generated than on my phone's authenticator app initialized with the same secret.

**Comment by juergenhoetzel** [comment]
> 13 space-separated blocks of 4 capital letters/digits each

`13*4` base32 chars (`13*4*5=260` bits) is not a valid length. You need to add  the padding `====` to get the next valid length.   

I have successfully setup a 256 bit Amazon shared secret using the additional `====` padding
and using the `base32` option `-c 32`  to prevent the line break.

**Comment by juergenhoetzel** [comment]
I added a `python` oneliner to the README for non-standard base32 encodings.

**Comment by tsdh** [comment]
@juergenhoetzel Very cool, thanks a lot!
